# Generated by Django 4.0.4 on 2022-04-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_name_delete_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Item',
        ),
    ]
